version: 2
jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:v1.19.1
    steps:
      - checkout
      - run:
          name: "Run golangci-lint"
          command: golangci-lint run --color always --enable-all --exclude-use-default -D godox -D gochecknoglobals -D gochecknoinits -D lll -D funlen -D whitespace
  critic:
    docker:
      - image: jakewarren/gocritic:latest
    steps:
      - checkout
      - run:
          name: "Run gocritic"
          command: gocritic check -enableAll -coloredOutput || true
  test:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run:
          name: "Run tests"
          command: |
            make test

  release:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test
      - critic
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/